# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for examples

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
  # Version specifiers for each tool. It must contain at least one tool.
  # Tool options include: python, nodejs, rust, golang
    python: "3.10"

# Optionally declare the Python requirements required to build your docs
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
# Configuration for Sphinx documentation (this is the default documentation type).
sphinx:
  # The builder type for the Sphinx documentation.
  # Options includs: html, dirhtml, singlehtml
  # builder: html
  # The path to the conf.py file, relative to the root of the project.
  # If the value is null, Read the Docs will try to find a conf.py file in your project.
  # configuration: conf.py
  # Turn warnings into errors (-W and --keep-going options). This means the build fails if there is a warning and exits with exit status 1.
  # The value is bool.
  # The default value is false
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
    - pdf
    - epub